name: Rust

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]  


    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build parser
      run: cargo build --verbose --package fsa-net-parser
    - name: Run parser tests
      run: cargo test --verbose --package fsa-net-parser
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    


